id: P009566
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:38:25.904884
source_metadata:
  id: bdr:W1KG4338
  title: རྩེ་ལེ་སྣ་ཚོགས་རང་གྲོལ་གྱི་གསུང་གདམས་ཟབ་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    4e68a3586c4b4f5989e67d9361269371:
      image_group_id: I1PD100509
      title: ''
      volume_number: 1
      total_pages: 588
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
